"""
Realistic Indian car market dataset covering all major segments.
Prices in INR Lakhs (ex-showroom), mileage in kmpl.
"""

CARS = [
    # ─── HATCHBACKS ───────────────────────────────────────────────────────────
    {
        "id": "maruti-alto-k10",
        "make": "Maruti Suzuki", "model": "Alto K10", "variant": "VXI",
        "type": "Hatchback", "segment": "entry",
        "price_lakh": 3.99, "fuel": "Petrol", "transmission": "Manual",
        "mileage_kmpl": 24.39, "engine_cc": 998, "seats": 5,
        "boot_litres": 214, "safety_rating": 2,
        "features": ["power steering", "front AC"],
        "pros": ["Cheapest to run", "Easy to park", "Low maintenance"],
        "cons": ["No airbags standard", "Very basic interior", "Underpowered on highways"],
        "best_for": ["first car", "city commute", "tight budget"],
        "monthly_emi_approx": 8200,
    },
    {
        "id": "maruti-wagonr",
        "make": "Maruti Suzuki", "model": "WagonR", "variant": "ZXI Plus",
        "type": "Hatchback", "segment": "budget",
        "price_lakh": 6.99, "fuel": "Petrol", "transmission": "AMT",
        "mileage_kmpl": 24.43, "engine_cc": 1197, "seats": 5,
        "boot_litres": 341, "safety_rating": 3,
        "features": ["dual airbags", "ABS", "rear camera", "auto gear"],
        "pros": ["Tall-boy design = huge space", "Excellent mileage", "Easy drive"],
        "cons": ["Boxy looks divide opinion", "Noisy at highway speeds"],
        "best_for": ["family city car", "senior citizens", "ride-share"],
        "monthly_emi_approx": 14400,
    },
    {
        "id": "tata-tiago",
        "make": "Tata", "model": "Tiago", "variant": "XZ+ CNG",
        "type": "Hatchback", "segment": "budget",
        "price_lakh": 7.45, "fuel": "CNG", "transmission": "Manual",
        "mileage_kmpl": 26.49, "engine_cc": 1199, "seats": 5,
        "boot_litres": 242, "safety_rating": 4,
        "features": ["6 airbags", "ABS", "Bluetooth", "rear camera"],
        "pros": ["5-star GNCAP safety", "Ultra-low running cost", "Good build quality"],
        "cons": ["CNG boot compromise", "Less power than petrol"],
        "best_for": ["safety-conscious buyers", "high daily mileage", "cost efficiency"],
        "monthly_emi_approx": 15300,
    },
    {
        "id": "hyundai-i20",
        "make": "Hyundai", "model": "i20", "variant": "Sportz Turbo DCT",
        "type": "Hatchback", "segment": "premium-hatch",
        "price_lakh": 10.50, "fuel": "Petrol", "transmission": "DCT",
        "mileage_kmpl": 19.65, "engine_cc": 998, "seats": 5,
        "boot_litres": 311, "safety_rating": 3,
        "features": ["turbo engine", "sunroof", "wireless charging", "BOSE audio", "BlueLink connected"],
        "pros": ["Fun to drive", "Feature-rich cabin", "Sharp looks"],
        "cons": ["Expensive to service", "Back seat tight for 3"],
        "best_for": ["enthusiasts", "young professionals", "feature lovers"],
        "monthly_emi_approx": 21600,
    },
    {
        "id": "maruti-baleno",
        "make": "Maruti Suzuki", "model": "Baleno", "variant": "Alpha CNG",
        "type": "Hatchback", "segment": "premium-hatch",
        "price_lakh": 9.49, "fuel": "CNG", "transmission": "Manual",
        "mileage_kmpl": 30.61, "engine_cc": 1197, "seats": 5,
        "boot_litres": 318, "safety_rating": 3,
        "features": ["HUD", "360-camera", "wireless carplay", "auto climate"],
        "pros": ["Best-in-class mileage", "Huge feature list", "Wide service network"],
        "cons": ["Safety rating lags peers", "CNG boot space lost"],
        "best_for": ["mileage priority", "tech lovers", "daily long commute"],
        "monthly_emi_approx": 19500,
    },
    {
        "id": "volkswagen-polo",
        "make": "Volkswagen", "model": "Polo", "variant": "GT TSI",
        "type": "Hatchback", "segment": "premium-hatch",
        "price_lakh": 10.99, "fuel": "Petrol", "transmission": "Automatic",
        "mileage_kmpl": 16.47, "engine_cc": 999, "seats": 5,
        "boot_litres": 280, "safety_rating": 4,
        "features": ["turbo", "rain sensing wipers", "auto headlamps"],
        "pros": ["European build quality", "Very fun to drive", "Ages well"],
        "cons": ["High service cost", "Limited feature list vs price", "Discontinued but available as new stock"],
        "best_for": ["driving enthusiasts", "build quality priority", "weekend driver"],
        "monthly_emi_approx": 22600,
    },

    # ─── SEDANS ───────────────────────────────────────────────────────────────
    {
        "id": "maruti-dzire",
        "make": "Maruti Suzuki", "model": "Dzire", "variant": "ZXI Plus AMT",
        "type": "Sedan", "segment": "compact-sedan",
        "price_lakh": 9.69, "fuel": "Petrol", "transmission": "AMT",
        "mileage_kmpl": 24.12, "engine_cc": 1197, "seats": 5,
        "boot_litres": 378, "safety_rating": 3,
        "features": ["auto gear", "rear AC", "cruise control", "apple carplay"],
        "pros": ["Massive 378L boot", "Excellent mileage", "Easy AMT in traffic"],
        "cons": ["AMT jerky at low speeds", "Uninspiring styling"],
        "best_for": ["cab operators", "outstation travel", "boot space priority"],
        "monthly_emi_approx": 19900,
    },
    {
        "id": "honda-city",
        "make": "Honda", "model": "City", "variant": "ZX CVT",
        "type": "Sedan", "segment": "mid-sedan",
        "price_lakh": 16.45, "fuel": "Petrol", "transmission": "CVT",
        "mileage_kmpl": 18.8, "engine_cc": 1498, "seats": 5,
        "boot_litres": 506, "safety_rating": 5,
        "features": ["Honda Sensing ADAS", "sunroof", "wireless carplay", "lane keep assist", "collision mitigation"],
        "pros": ["Best-in-class safety tech", "Refined 1.5L engine", "Premium cabin"],
        "cons": ["Expensive for segment", "CVT not sporty"],
        "best_for": ["safety-first families", "highway cruising", "executive use"],
        "monthly_emi_approx": 33800,
    },
    {
        "id": "hyundai-verna",
        "make": "Hyundai", "model": "Verna", "variant": "SX Turbo DCT",
        "type": "Sedan", "segment": "mid-sedan",
        "price_lakh": 17.49, "fuel": "Petrol", "transmission": "DCT",
        "mileage_kmpl": 20.0, "engine_cc": 998, "seats": 5,
        "boot_litres": 528, "safety_rating": 4,
        "features": ["ADAS", "panoramic sunroof", "ventilated seats", "10.25\" screen", "BlueLink"],
        "pros": ["Loaded with features", "Fun turbo engine", "Segment-leading space"],
        "cons": ["Complex electronics can be glitchy", "Expensive top variant"],
        "best_for": ["feature maximalists", "long highway trips", "status symbol"],
        "monthly_emi_approx": 35900,
    },
    {
        "id": "skoda-slavia",
        "make": "Skoda", "model": "Slavia", "variant": "Style 1.5 TSI DSG",
        "type": "Sedan", "segment": "mid-sedan",
        "price_lakh": 18.49, "fuel": "Petrol", "transmission": "DSG",
        "mileage_kmpl": 19.6, "engine_cc": 1498, "seats": 5,
        "boot_litres": 521, "safety_rating": 5,
        "features": ["6 airbags", "ADAS", "ventilated seats", "Canton audio"],
        "pros": ["Best driving dynamics in segment", "5-star safety", "Premium feel"],
        "cons": ["Service expensive", "Less dealer network"],
        "best_for": ["driver-focused buyers", "European brand loyalists", "highway cruisers"],
        "monthly_emi_approx": 38000,
    },

    # ─── COMPACT SUVs ─────────────────────────────────────────────────────────
    {
        "id": "maruti-brezza",
        "make": "Maruti Suzuki", "model": "Brezza", "variant": "ZXI+ AT",
        "type": "Compact SUV", "segment": "compact-suv",
        "price_lakh": 13.49, "fuel": "Petrol", "transmission": "Automatic",
        "mileage_kmpl": 19.8, "engine_cc": 1462, "seats": 5,
        "boot_litres": 328, "safety_rating": 3,
        "features": ["sunroof", "HUD", "wireless carplay", "arkamys audio", "auto climate"],
        "pros": ["Most reliable in segment", "Cheapest service", "Wide network"],
        "cons": ["Average safety rating", "No diesel option", "Interior feels budget"],
        "best_for": ["reliability priority", "resale value", "low ownership cost"],
        "monthly_emi_approx": 27700,
    },
    {
        "id": "tata-nexon",
        "make": "Tata", "model": "Nexon", "variant": "Creative+ S",
        "type": "Compact SUV", "segment": "compact-suv",
        "price_lakh": 14.49, "fuel": "Petrol", "transmission": "Automatic",
        "mileage_kmpl": 17.4, "engine_cc": 1199, "seats": 5,
        "boot_litres": 350, "safety_rating": 5,
        "features": ["5-star GNCAP", "panoramic sunroof", "JBL audio", "ADAS", "360 camera"],
        "pros": ["Highest safety rating in segment", "Rugged looks", "Great feature value"],
        "cons": ["Slightly rough ride", "Turbo-petrol needs premium fuel"],
        "best_for": ["safety-first families", "young buyers", "style-conscious"],
        "monthly_emi_approx": 29800,
    },
    {
        "id": "tata-nexon-ev",
        "make": "Tata", "model": "Nexon EV", "variant": "Fearless+ LR",
        "type": "Compact SUV", "segment": "compact-suv",
        "price_lakh": 17.49, "fuel": "Electric", "transmission": "Automatic",
        "mileage_kmpl": 0, "engine_cc": 0, "seats": 5,
        "range_km": 453, "safety_rating": 5,
        "features": ["453km range", "fast charging", "5-star GNCAP", "ADAS", "JBL audio", "vehicle-to-load"],
        "pros": ["Lowest running cost (~1.5 Rs/km)", "No petrol dependency", "Excellent safety"],
        "cons": ["High upfront cost", "Charging infrastructure still developing"],
        "best_for": ["tech adopters", "city-heavy usage", "environment-conscious", "home charging available"],
        "monthly_emi_approx": 35900,
    },
    {
        "id": "hyundai-venue",
        "make": "Hyundai", "model": "Venue", "variant": "S+ DCT",
        "type": "Compact SUV", "segment": "compact-suv",
        "price_lakh": 12.99, "fuel": "Petrol", "transmission": "DCT",
        "mileage_kmpl": 18.15, "engine_cc": 998, "seats": 5,
        "boot_litres": 350, "safety_rating": 3,
        "features": ["connected car tech", "auto climate", "wireless carplay", "BlueLink 60+ features"],
        "pros": ["Best connectivity features", "Smooth DCT auto", "Compact for city"],
        "cons": ["Average safety", "Smaller than rivals", "Back seat cramped"],
        "best_for": ["city-only buyers", "tech lovers", "compact parking"],
        "monthly_emi_approx": 26700,
    },
    {
        "id": "kia-sonet",
        "make": "Kia", "model": "Sonet", "variant": "GTX+ 1.5 Diesel AT",
        "type": "Compact SUV", "segment": "compact-suv",
        "price_lakh": 15.79, "fuel": "Diesel", "transmission": "Automatic",
        "mileage_kmpl": 19.35, "engine_cc": 1493, "seats": 5,
        "boot_litres": 392, "safety_rating": 3,
        "features": ["Bose audio", "ventilated seats", "wireless charging", "sunroof", "ADAS"],
        "pros": ["Best feature-per-rupee", "Diesel auto rare in segment", "Premium interior"],
        "cons": ["Average safety", "Kia service network smaller than Hyundai"],
        "best_for": ["diesel auto seekers", "feature-per-rupee value", "long highway use"],
        "monthly_emi_approx": 32400,
    },
    {
        "id": "renault-kiger",
        "make": "Renault", "model": "Kiger", "variant": "RXT Turbo CVT",
        "type": "Compact SUV", "segment": "compact-suv",
        "price_lakh": 9.99, "fuel": "Petrol", "transmission": "CVT",
        "mileage_kmpl": 18.28, "engine_cc": 999, "seats": 5,
        "boot_litres": 405, "safety_rating": 3,
        "features": ["405L boot", "8\" touchscreen", "wireless carplay"],
        "pros": ["Largest boot in subcompact SUV", "Affordable CVT", "Light and easy to drive"],
        "cons": ["Renault service network patchy", "Interior quality average"],
        "best_for": ["budget SUV lovers", "luggage priority", "first SUV"],
        "monthly_emi_approx": 20500,
    },

    # ─── MID-SIZE SUVs ────────────────────────────────────────────────────────
    {
        "id": "hyundai-creta",
        "make": "Hyundai", "model": "Creta", "variant": "SX(O) Turbo DCT",
        "type": "Mid-size SUV", "segment": "mid-suv",
        "price_lakh": 19.99, "fuel": "Petrol", "transmission": "DCT",
        "mileage_kmpl": 16.8, "engine_cc": 1482, "seats": 5,
        "boot_litres": 433, "safety_rating": 3,
        "features": ["panoramic sunroof", "ADAS Level 2", "BOSE audio", "360 camera", "ventilated seats", "BlueLink", "digital cockpit"],
        "pros": ["Best-selling mid SUV for a reason", "Massive feature list", "Strong resale"],
        "cons": ["Safety rating disappointing for price", "Waiting period often long"],
        "best_for": ["families", "all-rounder buyer", "resale value", "prestige"],
        "monthly_emi_approx": 41100,
    },
    {
        "id": "kia-seltos",
        "make": "Kia", "model": "Seltos", "variant": "X-Line 1.5 Turbo DCT",
        "type": "Mid-size SUV", "segment": "mid-suv",
        "price_lakh": 20.99, "fuel": "Petrol", "transmission": "DCT",
        "mileage_kmpl": 16.0, "engine_cc": 1482, "seats": 5,
        "boot_litres": 433, "safety_rating": 4,
        "features": ["dual PIVI Pro screens", "Meridian audio", "ADAS", "panoramic sunroof", "HUD", "360 camera"],
        "pros": ["Most premium interior in segment", "Better safety than Creta", "Sporty X-Line looks"],
        "cons": ["Expensive at top trim", "Kia dealer slightly less than Hyundai"],
        "best_for": ["interior quality seekers", "tech enthusiasts", "style-first buyers"],
        "monthly_emi_approx": 43100,
    },
    {
        "id": "maruti-grand-vitara",
        "make": "Maruti Suzuki", "model": "Grand Vitara", "variant": "Alpha+ e:HEV",
        "type": "Mid-size SUV", "segment": "mid-suv",
        "price_lakh": 19.49, "fuel": "Hybrid", "transmission": "Automatic",
        "mileage_kmpl": 27.97, "engine_cc": 1490, "seats": 5,
        "boot_litres": 373, "safety_rating": 3,
        "features": ["strong hybrid", "HUD", "panoramic sunroof", "360 camera", "wireless carplay"],
        "pros": ["Best mileage in mid-SUV segment by far", "Tax benefits (hybrid)", "Smooth hybrid power"],
        "cons": ["Smaller boot", "Safety rating average", "More expensive than Creta base"],
        "best_for": ["mileage-obsessed buyers", "daily 100km+ commuters", "eco-conscious families"],
        "monthly_emi_approx": 40000,
    },
    {
        "id": "toyota-hyryder",
        "make": "Toyota", "model": "Hyryder", "variant": "V Hybrid 2WD",
        "type": "Mid-size SUV", "segment": "mid-suv",
        "price_lakh": 17.99, "fuel": "Hybrid", "transmission": "Automatic",
        "mileage_kmpl": 27.97, "engine_cc": 1490, "seats": 5,
        "boot_litres": 373, "safety_rating": 3,
        "features": ["strong hybrid", "Toyota Safety Sense", "panoramic sunroof", "wireless carplay"],
        "pros": ["Toyota reliability reputation", "Same class-leading mileage as Grand Vitara", "Toyota resale value"],
        "cons": ["Same compromises as Grand Vitara", "Toyota premium pricing"],
        "best_for": ["Toyota loyalists", "reliability + mileage combo", "long-term ownership"],
        "monthly_emi_approx": 36900,
    },
    {
        "id": "volkswagen-taigun",
        "make": "Volkswagen", "model": "Taigun", "variant": "GT Plus 1.5 DSG",
        "type": "Mid-size SUV", "segment": "mid-suv",
        "price_lakh": 19.99, "fuel": "Petrol", "transmission": "DSG",
        "mileage_kmpl": 17.58, "engine_cc": 1498, "seats": 5,
        "boot_litres": 385, "safety_rating": 5,
        "features": ["5-star GNCAP", "travel assist ADAS", "IQ.DRIVE", "ambient lighting", "Canton audio"],
        "pros": ["5-star safety leader", "Best driving dynamics in segment", "Build quality class-apart"],
        "cons": ["Service expensive", "Fewer Volkswagen dealers"],
        "best_for": ["safety + driving dynamics", "Euro build quality seekers", "long highway drivers"],
        "monthly_emi_approx": 41100,
    },
    {
        "id": "skoda-kushaq",
        "make": "Skoda", "model": "Kushaq", "variant": "Monte Carlo 1.5 DSG",
        "type": "Mid-size SUV", "segment": "mid-suv",
        "price_lakh": 19.49, "fuel": "Petrol", "transmission": "DSG",
        "mileage_kmpl": 17.25, "engine_cc": 1498, "seats": 5,
        "boot_litres": 385, "safety_rating": 5,
        "features": ["5-star GNCAP", "ADAS", "Canton audio", "ambient lighting", "wireless carplay"],
        "pros": ["5-star safety", "Sporty Monte Carlo looks", "European refinement"],
        "cons": ["Small dealer network", "High service cost"],
        "best_for": ["style + safety", "enthusiast drivers", "brand differentiators"],
        "monthly_emi_approx": 40000,
    },
    {
        "id": "mg-astor",
        "make": "MG", "model": "Astor", "variant": "Savvy CVT",
        "type": "Mid-size SUV", "segment": "mid-suv",
        "price_lakh": 17.49, "fuel": "Petrol", "transmission": "CVT",
        "mileage_kmpl": 15.87, "engine_cc": 1349, "seats": 5,
        "boot_litres": 423, "safety_rating": 3,
        "features": ["built-in AI assistant", "ADAS Level 2", "360 camera", "heated seats", "panoramic sunroof"],
        "pros": ["Unique AI voice assistant inside car", "Feature-packed", "Good interior space"],
        "cons": ["MG (SAIC) ownership concerns for some buyers", "Lower resale than Hyundai/Kia"],
        "best_for": ["feature explorers", "tech first-movers", "MG loyalists"],
        "monthly_emi_approx": 35900,
    },

    # ─── 7-SEATER SUVs ────────────────────────────────────────────────────────
    {
        "id": "tata-safari",
        "make": "Tata", "model": "Safari", "variant": "Adventure Persona 6S",
        "type": "7-Seater SUV", "segment": "7-seater-suv",
        "price_lakh": 21.49, "fuel": "Diesel", "transmission": "Automatic",
        "mileage_kmpl": 16.15, "engine_cc": 1956, "seats": 7,
        "boot_litres": 447, "safety_rating": 5,
        "features": ["5-star GNCAP", "captain seats", "panoramic sunroof", "JBL audio", "ADAS", "terrain modes"],
        "pros": ["5-star safety + 7 seats combo", "Imposing road presence", "Best value 7-seater"],
        "cons": ["Ride quality slightly firm", "3rd row tight for adults"],
        "best_for": ["large families", "safety-conscious 7-seater", "road trips"],
        "monthly_emi_approx": 44100,
    },
    {
        "id": "mahindra-xuv700",
        "make": "Mahindra", "model": "XUV700", "variant": "AX7 Diesel AWD AT",
        "type": "7-Seater SUV", "segment": "7-seater-suv",
        "price_lakh": 26.99, "fuel": "Diesel", "transmission": "Automatic",
        "mileage_kmpl": 15.21, "engine_cc": 2184, "seats": 7,
        "boot_litres": 500, "safety_rating": 5,
        "features": ["ADAS Level 2", "AWD", "panoramic sunroof", "Sony 3D audio", "AdrenoX AI"],
        "pros": ["Technology showcased at any price", "AWD available", "Genuine 7-seater"],
        "cons": ["Long waiting period", "Electronics can need updates"],
        "best_for": ["tech showcase buyers", "AWD off-road", "large family highway"],
        "monthly_emi_approx": 55400,
    },
    {
        "id": "hyundai-alcazar",
        "make": "Hyundai", "model": "Alcazar", "variant": "Signature Diesel AT 7S",
        "type": "7-Seater SUV", "segment": "7-seater-suv",
        "price_lakh": 21.49, "fuel": "Diesel", "transmission": "Automatic",
        "mileage_kmpl": 17.5, "engine_cc": 1493, "seats": 7,
        "boot_litres": 180, "safety_rating": 3,
        "features": ["panoramic sunroof", "captain seats", "Bose audio", "ADAS", "ambient lighting"],
        "pros": ["Comfortable captain seats", "Hyundai reliability", "Good highway mileage for diesel"],
        "cons": ["Small boot with 7 seats", "Average safety for price"],
        "best_for": ["comfort-first 7-seater", "Hyundai loyalists", "captain seat preference"],
        "monthly_emi_approx": 44100,
    },
    {
        "id": "mahindra-scorpio-n",
        "make": "Mahindra", "model": "Scorpio N", "variant": "Z8L Diesel MT 4WD",
        "type": "7-Seater SUV", "segment": "7-seater-suv",
        "price_lakh": 23.99, "fuel": "Diesel", "transmission": "Manual",
        "mileage_kmpl": 14.52, "engine_cc": 2184, "seats": 7,
        "boot_litres": 468, "safety_rating": 5,
        "features": ["5-star GNCAP", "4WD", "panoramic sunroof", "Harman Kardon audio", "terrain modes"],
        "pros": ["Real 4WD off-road capability", "5-star safety", "Iconic Indian SUV"],
        "cons": ["Manual only in 4WD trim", "Thirsty in city", "Large size harder to park"],
        "best_for": ["off-road adventure", "rural terrain", "SUV enthusiasts", "7-seat + 4WD"],
        "monthly_emi_approx": 49300,
    },

    # ─── PREMIUM & LUXURY ─────────────────────────────────────────────────────
    {
        "id": "jeep-meridian",
        "make": "Jeep", "model": "Meridian", "variant": "4x4 Limited (O)",
        "type": "7-Seater SUV", "segment": "premium-suv",
        "price_lakh": 36.95, "fuel": "Diesel", "transmission": "Automatic",
        "mileage_kmpl": 14.26, "engine_cc": 1956, "seats": 7,
        "boot_litres": 700, "safety_rating": 5,
        "features": ["4x4 Selec-Terrain", "panoramic sunroof", "McIntosh audio", "ADAS", "9 airbags"],
        "pros": ["Only mass-market 7S with proper 4x4", "Unmatched off-road + comfort combo", "Premium badge"],
        "cons": ["High price", "Jeep service network limited"],
        "best_for": ["premium off-road", "luxury 7-seater", "adventure + family"],
        "monthly_emi_approx": 75900,
    },
    {
        "id": "toyota-fortuner",
        "make": "Toyota", "model": "Fortuner", "variant": "4x4 AT Legender",
        "type": "7-Seater SUV", "segment": "premium-suv",
        "price_lakh": 46.77, "fuel": "Diesel", "transmission": "Automatic",
        "mileage_kmpl": 10.02, "engine_cc": 2755, "seats": 7,
        "boot_litres": 396, "safety_rating": 4,
        "features": ["4x4", "bi-LED matrix headlamps", "JBL audio", "terrain modes"],
        "pros": ["Aspirational benchmark SUV", "Toyota bulletproof reliability", "Incredible resale value"],
        "cons": ["Expensive", "Fuel cost significant", "Old platform"],
        "best_for": ["status symbol", "business use", "long-term value", "tough terrain"],
        "monthly_emi_approx": 96100,
    },
    {
        "id": "mg-gloster",
        "make": "MG", "model": "Gloster", "variant": "Savvy 4WD",
        "type": "7-Seater SUV", "segment": "premium-suv",
        "price_lakh": 42.49, "fuel": "Diesel", "transmission": "Automatic",
        "mileage_kmpl": 12.51, "engine_cc": 1996, "seats": 7,
        "boot_litres": 510, "safety_rating": 4,
        "features": ["L2+ autonomous driving", "4WD", "360 camera", "12-speaker audio", "massage seats"],
        "pros": ["Best L2 autonomous tech at price", "Luxury features at Fortuner price", "Huge cabin"],
        "cons": ["MG brand perception", "Fuel costs high"],
        "best_for": ["tech-first premium buyer", "luxury under 45L", "family comfort"],
        "monthly_emi_approx": 87300,
    },

    # ─── MPVs & VANS ──────────────────────────────────────────────────────────
    {
        "id": "kia-carens",
        "make": "Kia", "model": "Carens", "variant": "Luxury Plus 1.5 Diesel AT",
        "type": "MPV", "segment": "mpv",
        "price_lakh": 19.99, "fuel": "Diesel", "transmission": "Automatic",
        "mileage_kmpl": 20.11, "engine_cc": 1493, "seats": 7,
        "boot_litres": 551, "safety_rating": 3,
        "features": ["7 seats", "panoramic sunroof", "Bose audio", "wireless charging", "ADAS"],
        "pros": ["Best value 7-seater MPV", "Good diesel mileage", "Comfortable 3 rows"],
        "cons": ["3rd row best for kids", "MPV styling not for everyone"],
        "best_for": ["school run families", "7 adults on budget", "outstation trips"],
        "monthly_emi_approx": 41100,
    },
    {
        "id": "toyota-innova-hycross",
        "make": "Toyota", "model": "Innova Hycross", "variant": "ZX(O) Hybrid",
        "type": "MPV", "segment": "premium-mpv",
        "price_lakh": 28.99, "fuel": "Hybrid", "transmission": "e-CVT",
        "mileage_kmpl": 21.1, "engine_cc": 1987, "seats": 7,
        "boot_litres": 600, "safety_rating": 4,
        "features": ["strong hybrid", "captain seats", "panoramic sunroof", "JBL", "ambient lighting"],
        "pros": ["Spacious premium cabin", "Excellent hybrid mileage for size", "Toyota reliability"],
        "cons": ["Expensive", "Front-wheel drive only (unusual for class)"],
        "best_for": ["large family premium travel", "hotel/tour operators", "highway comfort"],
        "monthly_emi_approx": 59600,
    },
    {
        "id": "maruti-ertiga",
        "make": "Maruti Suzuki", "model": "Ertiga", "variant": "ZXI+ AT CNG",
        "type": "MPV", "segment": "mpv",
        "price_lakh": 13.49, "fuel": "CNG", "transmission": "Automatic",
        "mileage_kmpl": 26.11, "engine_cc": 1462, "seats": 7,
        "boot_litres": 803, "safety_rating": 3,
        "features": ["7 seats", "auto gear", "rear AC", "wireless carplay"],
        "pros": ["Cheapest auto 7-seater", "CNG = ultra-low running cost", "Reliable Maruti"],
        "cons": ["Basic interior", "CNG auto is relatively rare, sometimes availability issues"],
        "best_for": ["family on budget", "cab operators", "low running cost 7-seater"],
        "monthly_emi_approx": 27700,
    },

    # ─── ELECTRIC VEHICLES ────────────────────────────────────────────────────
    {
        "id": "tata-punch-ev",
        "make": "Tata", "model": "Punch EV", "variant": "Empowered+ LR",
        "type": "Compact SUV", "segment": "compact-suv",
        "price_lakh": 13.99, "fuel": "Electric", "transmission": "Automatic",
        "mileage_kmpl": 0, "engine_cc": 0, "seats": 5,
        "range_km": 421, "safety_rating": 5,
        "features": ["421km range", "V2L/V2V", "5-star GNCAP", "10.25\" screen", "connected tech"],
        "pros": ["Cheapest long-range EV", "5-star safety", "V2L power outlet"],
        "cons": ["Smaller than Nexon EV", "Ground clearance lower than Nexon"],
        "best_for": ["entry-level EV buyers", "city + occasional highway", "home charging owners"],
        "monthly_emi_approx": 28700,
    },
    {
        "id": "mg-zs-ev",
        "make": "MG", "model": "ZS EV", "variant": "Excite Pro",
        "type": "Mid-size SUV", "segment": "mid-suv",
        "price_lakh": 18.98, "fuel": "Electric", "transmission": "Automatic",
        "mileage_kmpl": 0, "engine_cc": 0, "seats": 5,
        "range_km": 461, "safety_rating": 4,
        "features": ["461km range", "fast charging", "panoramic sunroof", "ADAS", "air purifier"],
        "pros": ["Good range", "Spacious mid-SUV EV", "ADAS level 2"],
        "cons": ["MG charging network smaller", "Brand perception"],
        "best_for": ["EV mid-SUV seekers", "city + intercity EV use"],
        "monthly_emi_approx": 39000,
    },
    {
        "id": "hyundai-ioniq5",
        "make": "Hyundai", "model": "Ioniq 5", "variant": "RWD Standard Range",
        "type": "Mid-size SUV", "segment": "premium-suv",
        "price_lakh": 46.05, "fuel": "Electric", "transmission": "Automatic",
        "mileage_kmpl": 0, "engine_cc": 0, "seats": 5,
        "range_km": 631, "safety_rating": 5,
        "features": ["631km range", "800V ultra-fast charging", "V2L", "futuristic interior", "ADAS Level 2"],
        "pros": ["Best EV tech available in India", "Ultra-fast 800V charging", "Global premium EV"],
        "cons": ["Very expensive", "No AWD in this variant"],
        "best_for": ["premium EV adopters", "tech showcasers", "long range EV travel"],
        "monthly_emi_approx": 94700,
    },
    {
        "id": "byd-seal",
        "make": "BYD", "model": "Seal", "variant": "Dynamic AWD",
        "type": "Sedan", "segment": "premium-sedan",
        "price_lakh": 41.0, "fuel": "Electric", "transmission": "Automatic",
        "mileage_kmpl": 0, "engine_cc": 0, "seats": 5,
        "range_km": 650, "safety_rating": 5,
        "features": ["650km range", "AWD", "Blade Battery", "rotating screen", "ADAS"],
        "pros": ["Performance EV sedan at Tesla price", "Blade battery safety", "AWD grip"],
        "cons": ["BYD service network still expanding in India", "Chinese brand perception"],
        "best_for": ["performance EV sedan lovers", "Tesla alternative seekers"],
        "monthly_emi_approx": 84300,
    },

    # ─── SPORTS & PERFORMANCE ─────────────────────────────────────────────────
    {
        "id": "hyundai-i20-n-line",
        "make": "Hyundai", "model": "i20 N Line", "variant": "N8 Turbo DCT",
        "type": "Hatchback", "segment": "hot-hatch",
        "price_lakh": 13.49, "fuel": "Petrol", "transmission": "DCT",
        "mileage_kmpl": 17.71, "engine_cc": 998, "seats": 5,
        "boot_litres": 311, "safety_rating": 3,
        "features": ["N-tuned suspension", "N-button for sport modes", "red accents", "Bose audio", "paddle shifters"],
        "pros": ["Most fun daily driver under 15L", "Sporty looks + drive", "Daily usable"],
        "cons": ["Stiff ride", "Only 5 seats", "Mileage suffers in sport mode"],
        "best_for": ["driving enthusiasts", "weekend fun + daily commute", "performance on budget"],
        "monthly_emi_approx": 27700,
    },
    {
        "id": "mg-hector",
        "make": "MG", "model": "Hector", "variant": "Select Sharp Pro",
        "type": "Mid-size SUV", "segment": "mid-suv",
        "price_lakh": 18.99, "fuel": "Petrol", "transmission": "Automatic",
        "mileage_kmpl": 14.63, "engine_cc": 1451, "seats": 5,
        "boot_litres": 587, "safety_rating": 3,
        "features": ["14\" touchscreen", "ADAS", "panoramic sunroof", "air purifier", "wireless carplay"],
        "pros": ["Biggest screen in segment", "Large cabin", "Feature-rich at price"],
        "cons": ["Below-average mileage", "MG brand concerns", "Older platform"],
        "best_for": ["screen size obsessives", "large cabin seekers", "MG loyalists"],
        "monthly_emi_approx": 39000,
    },
    {
        "id": "mahindra-thar",
        "make": "Mahindra", "model": "Thar Roxx", "variant": "MX5 Diesel 4WD AT",
        "type": "Compact SUV", "segment": "off-road",
        "price_lakh": 18.99, "fuel": "Diesel", "transmission": "Automatic",
        "mileage_kmpl": 15.2, "engine_cc": 2184, "seats": 5,
        "boot_litres": 428, "safety_rating": 5,
        "features": ["4WD", "5-star GNCAP", "terrain modes", "panoramic sunroof", "Sony audio"],
        "pros": ["Off-road icon", "5-star safety", "5-door practicality of new Roxx"],
        "cons": ["Compromised city ride", "Thirsty off-tarmac"],
        "best_for": ["off-road adventures", "SUV lifestyle", "weekend explorers"],
        "monthly_emi_approx": 39000,
    },
]

# Segment display names for UI
SEGMENT_LABELS = {
    "entry": "Entry Hatchback",
    "budget": "Budget Hatchback",
    "premium-hatch": "Premium Hatchback",
    "compact-sedan": "Compact Sedan",
    "mid-sedan": "Mid-size Sedan",
    "premium-sedan": "Premium Sedan",
    "compact-suv": "Compact SUV",
    "mid-suv": "Mid-size SUV",
    "premium-suv": "Premium SUV",
    "7-seater-suv": "7-Seater SUV",
    "mpv": "MPV / Van",
    "premium-mpv": "Premium MPV",
    "hot-hatch": "Hot Hatchback",
    "off-road": "Off-Road SUV",
}
